query SubcohortCounts($filter: SubcohortCountsFilter) {
  SubcohortCounts(filter: $filter) {
    subcohort {
      resource {
        pid
      }
      name
    }
    ageGroup {
      name
    }
  }
}
