query VariableMappings($filter: VariableMappingsFilter) {
  VariableMappings(filter: $filter) {
    source {
      id
    }
    sourceDataset {
      resource {
        id
        name
      }
      sinceVersion
      untilVersion
    }
    target {
      id
      name
    }
    targetDataset {
      resource {
        id
        name
      }
      sinceVersion
      untilVersion
    }
    targetVariable {
      resource {
        id
        name
      }
      dataset {
        resource{
          id
          name
        }
        name
        sinceVersion
        untilVersion
      }
      name
    }
  }
}