query VariableValues($filter: VariableValuesFilter) {
  VariableValues(filter: $filter) {
    resource{
      id
    }
    variable{
      dataset{
        name
      }
      name
    }
    value
    label
    order
    isMissing
    ontologyTermURI
    sinceVersion
    untilVersion
  }
}