class TablesToSync:
    NETWORK_STAGING_TO_DATA_CATALOGUE_ZIP = {
            'AllTargetVariables': None,
            'CollectionEvents': None,
            'Models': None,
            'Networks': None,
            'RepeatedTargetVariables': None,
            'Resources': None,
            'Subcohorts': None,
            'TargetDataDictionaries': None,
            'TargetTables': None,
            'TargetVariables': None,
            'TargetVariableValues': None,
        }
    COHORT_STAGING_TO_DATA_CATALOGUE_ZIP = {
            'Publications': None,
            'VariableMappings': None,
            'TableMappings': None,
            'SourceVariableValues': None,
            'RepeatedSourceVariables': None,
            'SourceVariables': None,
            'SourceTables': None,
            'SourceDataDictionaries': None,
            'Documentation': None,
            'Contributions': None,
            'CollectionEvents': None,
            'Subcohorts': None,
            'Partners': None,
            'Cohorts': None,
        }
    UMCG_COHORT_STAGING_TO_DATA_CATALOGUE_ZIP = {
            'Publications': None,
            'Documentation': None,
            'Contributions': None,
            'CollectionEvents': None,
            # 'Subcohorts': None,
            'Partners': None,
            'SubcohortCounts': None,
            'Subcohorts': None,
            'Resources': None,
            'Cohorts': None,
        }
    FILL_STAGING = {
            'Publications': None,
            'Cohorts': 'pid',
            'Documentation': 'resource',
            'Contributions': 'resource',
            'Subcohorts': 'resource',
            'CollectionEvents': 'resource',
            'Partners': 'resource',
            'SourceDataDictionaries': 'resource',
            'SourceTables': 'dataDictionary.resource',
            'SourceVariables': 'dataDictionary.resource',
            'RepeatedSourceVariables': 'dataDictionary.resource',
            'SourceVariableValues': 'dataDictionary.resource',
            'TableMappings': 'fromDataDictionary.resource',
            'VariableMappings': 'fromDataDictionary.resource',
        }
    SHARED_STAGING = {
            'Institutions': None,
            'Contacts': None,
        }
    FILL_NETWORK = {
            'Models': 'pid',
            'TargetDataDictionaries': 'resource',
            'TargetTables': 'dataDictionary.resource',
            'Subcohorts': 'resource',
            'CollectionEvents': 'resource',
            'TargetVariables': 'dataDictionary.resource',
            'TargetVariableValues': 'dataDictionary.resource',
            'RepeatedTargetVariables': 'dataDictionary.resource',
        }


class TablesToDelete:
    COHORT_STAGING_TO_DATA_CATALOGUE_ZIP = {
            'VariableMappings': 'mappings',
            'TableMappings': 'mappings',
            'SourceVariableValues': 'variables',
            'RepeatedSourceVariables': 'variables',
            'SourceVariables': 'variables',
            'SourceTables': 'variables',
            'SourceDataDictionaries': 'resource',
            'Documentation': 'resource',
            'Contributions': 'resource',
            'CollectionEvents': 'resource',
            'Subcohorts': 'resource',
            'Partners': 'resource',
            'Cohorts': 'pid',
        }
    UMCG_COHORT_STAGING_TO_DATA_CATALOGUE_ZIP = {
            'Publications': None,
            'Documentation': None,
            'Contributions': None,
            'CollectionEvents': None,
            # 'Subcohorts': None,
            'Partners': None,
            'SubcohortCounts': None,
            'Subcohorts': None,
            'Resources': None,
            'Cohorts': None,
        }


class OntologiesToSync:
    UMCG_SHARED_ONTOLOGY_ZIP = {
            'CoreVariables': None
        }
    ONTOLOGY_STAGING_TO_DATA_CATALOGUE_ZIP = {
            'AgeGroups': None,
            'AreasOfInformation': None,
            'CareSettings': None,
            'CohortDesigns': None,
            'CollectionTypes': None,
            'ContributionTypes': None,
            'CoreVariables': None,
            'Countries': None,
            'DAPsAccessCompleteness': None,
            'DAPsAccessLevels': None,
            'DAPsAccessPermissions': None,
            'DAPsReasonsForAccess': None,
            'DataAccessConditions': None,
            'DataCategories': None,
            'DataUseConditions': None,
            'DatabankFamilies': None,
            'DatasourceTypes': None,
            'Diseases': None,
            'DocumentTypes': None,
            'Formats': None,
            'InformedConsents': None,
            'InstitutionRoles': None,
            'InstitutionTypes': None,
            'Keywords': None,
            'Languages': None,
            'LinkageStrategies': None,
            'Months': None,
            'ObservationTargets': None,
            'PartnerRoles': None,
            'PopulationEntryCauses': None,
            'PopulationExitCauses': None,
            'PopulationSubsets': None,
            'Regions': None,
            'ReleaseTypes': None,
            'ResourceTypes': None,
            'SampleCategories': None,
            'StandardizedTools': None,
            'Status': None,
            'StatusDetails': None,
            'StudyTypes': None,
            'Titles': None,
            'Units': None,
            'Vocabularies': None,
            'Years': None,
        }
